cc_binary (
    name = "main",
    srcs = ["main.cpp"],
    deps = [
        ":output",
        "//current_time:current_time",
    ]
)

cc_library(
    name = "output",
    srcs = ["output.cpp"],
    hdrs = ["output.h"],
)
